// Offline Ed25519 licence verification.
//
// Two key formats are accepted:
//
//   KEYFIRE.<base64url(binary_payload)>.<base64url(signature)>   (current)
//     Binary payload: 10 bytes total
//       [0]     version = 0x01
//       [1]     tier    (0x01 = pro)
//       [2..6]  exp     u32 big-endian unix seconds
//       [6..10] id      u32 big-endian (rendered as 8-char lowercase hex)
//     Result: ~110 char total, ~54% shorter than the legacy format.
//     No email is signed into the payload — the CSV log at
//     %USERPROFILE%\.trigr\issued-keys.csv is the authoritative binding.
//
//   TRIGR-PRO.<base64url(payload_json)>.<base64url(signature)>   (legacy)
//     Payload JSON: { email, exp, tier, id }. Kept working forever so keys
//     already in the wild remain valid until they hit their exp timestamp.
//
// The signature is verified against PUBLIC_KEY_B64 (the base64 of the 32-byte
// Ed25519 public key produced by `cargo run -- init` inside
// src-tauri/trigr-keygen). Verification is fully local — no network, no
// LemonSqueezy, no phone-home.

use log::{error, info, warn};
use serde::{Deserialize, Serialize};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, OnceLock};

use base64::engine::general_purpose::URL_SAFE_NO_PAD as B64;
use base64::Engine;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};

// ── Public key ──────────────────────────────────────────────────────────────
//
// Generated by `cargo run -- init` inside src-tauri/trigr-keygen.
// Matching private key is held offline by the maintainer; do not commit the private key.
const PUBLIC_KEY_B64: &str = "SSYMRvcbW18DXRMoBWt4hdI8rOWg0dXJnW1h92cpZ80";

// ── Trial config ────────────────────────────────────────────────────────────
//
// 14-day Pro trial available to every install. Independent of any beta key —
// trial unlocks Pro features locally without contacting any server. Anti-abuse
// (uninstall to reset) is intentionally not handled during beta.
const TRIAL_DURATION_DAYS: i64 = 14;

// ── State ───────────────────────────────────────────────────────────────────

static IS_PRO: AtomicBool = AtomicBool::new(false);
static LICENCE_STATE: OnceLock<Mutex<LicenceState>> = OnceLock::new();

// ── Stored state ────────────────────────────────────────────────────────────

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct LicenceState {
    #[serde(default)]
    pub key: Option<String>,
    /// Present on legacy TRIGR-PRO keys only; absent on new KEYFIRE keys
    /// (email is no longer embedded in the signed payload).
    #[serde(default)]
    pub email: Option<String>,
    /// 8-char lowercase hex identifier for the issued key. Present on both
    /// key formats. Users can quote this to support to identify their key.
    #[serde(default)]
    pub key_id: Option<String>,
    #[serde(default)]
    pub tier: Option<String>,
    #[serde(default)]
    pub expires_at: Option<String>,
    #[serde(default)]
    pub activated_at: Option<String>,
    #[serde(default)]
    pub valid: bool,
    /// RFC3339 timestamp when the 14-day Pro trial was first started locally.
    /// Independent of any key; persists across reinstalls only if local settings survive.
    #[serde(default)]
    pub trial_started_at: Option<String>,
    /// True once the trial has been started. Prevents re-starting after expiry.
    #[serde(default)]
    pub trial_used: bool,
    /// True once the post-onboarding/migration trial offer has been shown to
    /// the user. Prevents the migration popup from firing on every launch.
    #[serde(default)]
    pub trial_offer_shown: bool,
}

/// Returned to the frontend for UI display.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LicenceStatus {
    pub is_pro: bool,
    pub key_entered: bool,
    pub status: String, // "no_key" | "active" | "expired" | "invalid"
    pub product_name: String,
    pub expires_at: Option<String>,
    /// Legacy TRIGR-PRO keys only. None for KEYFIRE keys.
    pub email: Option<String>,
    /// 8-char hex key identifier. Present on both formats when a key is active.
    pub key_id: Option<String>,
    /// True while the trial is active (started + not yet 14 days old).
    pub trial_active: bool,
    /// Whole days remaining on the trial (0 once expired). Always 0 if trial_active is false.
    pub trial_days_remaining: i64,
    /// True once start_trial has been called for this install. Stays true after expiry.
    pub trial_used: bool,
    /// True once the post-onboarding trial offer has been shown.
    pub trial_offer_shown: bool,
}

/// Legacy TRIGR-PRO JSON payload shape. Kept for backward compatibility only —
/// new keys use the compact binary layout described at the top of this file.
#[derive(Deserialize)]
struct LegacyPayload {
    email: String,
    exp: String,
    tier: String,
    #[serde(default)]
    id: Option<String>,
}

/// Unified shape produced by `verify_key` regardless of which key format was
/// pasted. Callers work off this instead of caring about the wire format.
struct DecodedKey {
    /// Legacy TRIGR-PRO keys only; None for KEYFIRE keys.
    email: Option<String>,
    /// RFC3339 UTC timestamp — same shape for both formats (v2 converts u32
    /// unix seconds to RFC3339 on decode so downstream code is unchanged).
    exp: String,
    tier: String,
    /// 8-char lowercase hex. Always Some for KEYFIRE keys; usually Some for
    /// legacy keys (older test keys may lack it — hence Option).
    id: Option<String>,
}

// ── Key format constants ────────────────────────────────────────────────────
const KEY_PREFIX_LEGACY: &str = "TRIGR-PRO.";
const KEY_PREFIX_V2: &str = "KEYFIRE.";
const PAYLOAD_V2_VERSION: u8 = 0x01;
const PAYLOAD_V2_TIER_PRO: u8 = 0x01;
const PAYLOAD_V2_LEN: usize = 10;

// ── Initialization ──────────────────────────────────────────────────────────

pub fn init() {
    let state = load_from_local_settings();
    let pro = compute_is_pro(&state);
    IS_PRO.store(pro, Ordering::SeqCst);
    let _ = LICENCE_STATE.set(Mutex::new(state));
    info!("[Keyfire] Licence module initialized — is_pro: {}", pro);
}

pub fn is_pro() -> bool {
    IS_PRO.load(Ordering::SeqCst)
}

/// True only when the user has a signature-valid, non-expired Pro key.
/// Unlike [`is_pro`], this does NOT return true for the trial fallback —
/// used by telemetry to keep beta-key holders on `pro` even while their
/// 14-day trial is still ticking.
pub fn has_valid_pro_key() -> bool {
    let state = match LICENCE_STATE.get() {
        Some(m) => m.lock().unwrap_or_else(|e| e.into_inner()).clone(),
        None => return false,
    };
    state.valid
        && state.tier.as_deref() == Some("pro")
        && state
            .expires_at
            .as_deref()
            .and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
            .map(|d| d.to_utc() > chrono::Utc::now())
            .unwrap_or(false)
}

pub fn get_licence_status() -> LicenceStatus {
    let state = match LICENCE_STATE.get() {
        Some(m) => m.lock().unwrap_or_else(|e| e.into_inner()).clone(),
        None => LicenceState::default(),
    };
    build_status(&state)
}

// ── API ─────────────────────────────────────────────────────────────────────

/// Verify a pasted licence key, store it locally, and unlock Pro.
///
/// Accepts KEYFIRE. (binary, current) and TRIGR-PRO. (legacy JSON) keys. The
/// canonical stored form is whatever the user pasted, minus any whitespace
/// picked up from email line-wrap.
pub async fn activate_licence(key: String) -> Result<LicenceStatus, String> {
    let decoded = verify_key(&key)?;
    let cleaned = strip_whitespace(&key);

    // Reject expired keys before saving.
    let exp_dt = chrono::DateTime::parse_from_rfc3339(&decoded.exp)
        .map_err(|_| "Key payload has an invalid expiry".to_string())?;
    if exp_dt.to_utc() < chrono::Utc::now() {
        return Err("This key has expired. Email admin@keyfire.app for a new one.".to_string());
    }

    let prior = match LICENCE_STATE.get() {
        Some(m) => m.lock().unwrap_or_else(|e| e.into_inner()).clone(),
        None => LicenceState::default(),
    };
    let state = LicenceState {
        key: Some(cleaned),
        email: decoded.email.clone(),
        key_id: decoded.id.clone(),
        tier: Some(decoded.tier.clone()),
        expires_at: Some(decoded.exp.clone()),
        activated_at: Some(chrono::Utc::now().to_rfc3339()),
        valid: true,
        trial_started_at: prior.trial_started_at,
        trial_used: prior.trial_used,
        trial_offer_shown: prior.trial_offer_shown,
    };
    update_state(state.clone());
    info!(
        "[Keyfire] Licence activated (id {}, tier {}, expires {})",
        decoded.id.as_deref().unwrap_or("-"), decoded.tier, decoded.exp
    );
    Ok(build_status(&state))
}

/// Start the 14-day Pro trial. Idempotent-ish: refuses to start if already used
/// (whether currently active or expired), so users can't reset by uninstalling
/// the *frontend* state — though full reinstall does reset everything (acceptable
/// during beta).
pub async fn start_trial() -> Result<LicenceStatus, String> {
    let mut state = match LICENCE_STATE.get() {
        Some(m) => m.lock().unwrap_or_else(|e| e.into_inner()).clone(),
        None => LicenceState::default(),
    };

    if state.trial_used {
        return Err("Trial has already been used on this install.".to_string());
    }

    state.trial_started_at = Some(chrono::Utc::now().to_rfc3339());
    state.trial_used = true;
    update_state(state.clone());
    info!(
        "[Keyfire] Pro trial started at {} ({} days)",
        state.trial_started_at.as_deref().unwrap_or(""),
        TRIAL_DURATION_DAYS
    );
    Ok(build_status(&state))
}

/// Mark the one-time post-onboarding (or migration) trial offer as shown.
/// Frontend calls this after displaying ProTrialModal to suppress repeat firings.
pub async fn mark_trial_offer_shown() -> LicenceStatus {
    let mut state = match LICENCE_STATE.get() {
        Some(m) => m.lock().unwrap_or_else(|e| e.into_inner()).clone(),
        None => LicenceState::default(),
    };
    if !state.trial_offer_shown {
        state.trial_offer_shown = true;
        update_state(state.clone());
        info!("[Keyfire] Trial offer marked as shown");
    }
    build_status(&state)
}

/// DEV/TEST ONLY: clear the local trial state (started / used / offer-shown) so
/// the 14-day trial and its post-onboarding announcement can be re-triggered.
/// Preserves any entered licence key. Exposed only via a dev-build button.
pub async fn reset_trial() -> LicenceStatus {
    let mut state = match LICENCE_STATE.get() {
        Some(m) => m.lock().unwrap_or_else(|e| e.into_inner()).clone(),
        None => LicenceState::default(),
    };
    state.trial_started_at = None;
    state.trial_used = false;
    state.trial_offer_shown = false;
    update_state(state.clone());
    info!("[Keyfire] Trial state reset (dev)");
    build_status(&state)
}

/// Clear the saved licence and drop back to Free. Preserves trial state so a
/// user who removes their key after the trial doesn't get a fresh 14 days.
pub async fn deactivate_licence() -> Result<LicenceStatus, String> {
    let prior = match LICENCE_STATE.get() {
        Some(m) => m.lock().unwrap_or_else(|e| e.into_inner()).clone(),
        None => LicenceState::default(),
    };
    let state = LicenceState {
        trial_started_at: prior.trial_started_at,
        trial_used: prior.trial_used,
        trial_offer_shown: prior.trial_offer_shown,
        ..LicenceState::default()
    };
    // ..Default explicitly zeros key_id back to None on deactivation.
    update_state(state.clone());
    info!("[Keyfire] Licence deactivated");
    Ok(build_status(&state))
}

/// Re-verify the saved key (signature + expiry). No network — exists to
/// handle the case where the user has crossed the expiry date since they
/// last opened the app.
pub async fn check_and_revalidate() -> LicenceStatus {
    let state = match LICENCE_STATE.get() {
        Some(m) => m.lock().unwrap_or_else(|e| e.into_inner()).clone(),
        None => return build_status(&LicenceState::default()),
    };

    let key = match &state.key {
        Some(k) if !k.is_empty() => k.clone(),
        _ => return build_status(&state),
    };

    match verify_key(&key) {
        Ok(decoded) => {
            let still_valid = chrono::DateTime::parse_from_rfc3339(&decoded.exp)
                .map(|d| d.to_utc() > chrono::Utc::now())
                .unwrap_or(false);
            let new_state = LicenceState {
                key: Some(key),
                email: decoded.email,
                key_id: decoded.id,
                tier: Some(decoded.tier),
                expires_at: Some(decoded.exp),
                activated_at: state.activated_at,
                valid: still_valid,
                trial_started_at: state.trial_started_at,
                trial_used: state.trial_used,
                trial_offer_shown: state.trial_offer_shown,
            };
            update_state(new_state.clone());
            build_status(&new_state)
        }
        Err(e) => {
            warn!("[Keyfire] Saved licence key failed re-verification: {}", e);
            let new_state = LicenceState {
                valid: false,
                ..state
            };
            update_state(new_state.clone());
            build_status(&new_state)
        }
    }
}

// ── Crypto + parsing ────────────────────────────────────────────────────────

/// Remove every whitespace char (space, tab, CR, LF, etc.) from the input.
///
/// Email clients (Gmail plaintext, some Outlook flows) wrap long strings at
/// ~76 chars, so users copy-pasting a licence key sometimes drop internal
/// whitespace into the middle of it. Stripping here fixes activation for
/// both TRIGR-PRO (existing keys in the wild) and KEYFIRE (new format).
fn strip_whitespace(s: &str) -> String {
    s.chars().filter(|c| !c.is_whitespace()).collect()
}

/// Verify a pasted licence key against the embedded Ed25519 public key.
///
/// Handles both formats:
///   - `KEYFIRE.<b64url(binary)>.<b64url(sig)>`  (current, ~110 chars)
///   - `TRIGR-PRO.<b64url(json)>.<b64url(sig)>`  (legacy, ~240 chars)
///
/// All whitespace is stripped up front, so line-wrapped emails paste cleanly.
fn verify_key(key: &str) -> Result<DecodedKey, String> {
    let clean = strip_whitespace(key);

    let verifying_key = load_public_key().map_err(|e| {
        format!(
            "This build of Keyfire is missing its signing public key ({}). \
             Please reinstall the latest version.",
            e
        )
    })?;

    // Order: check the newer, shorter prefix first — future volume will
    // be KEYFIRE keys, and TRIGR-PRO tails off as legacy keys expire.
    if let Some(body) = clean.strip_prefix(KEY_PREFIX_V2) {
        return verify_v2_binary(body, &verifying_key);
    }
    if let Some(body) = clean.strip_prefix(KEY_PREFIX_LEGACY) {
        return verify_legacy_json(body, &verifying_key);
    }
    Err("Not a Keyfire licence key".to_string())
}

/// Decode + verify a KEYFIRE. binary-payload key.
///
/// Payload layout (10 bytes, big-endian):
///   [0]     version = 0x01 (any other byte is a future format we don't know)
///   [1]     tier    (0x01 = pro)
///   [2..6]  exp     u32 unix seconds
///   [6..10] id      u32 (rendered as 8-char lowercase hex)
fn verify_v2_binary(body: &str, verifying_key: &VerifyingKey) -> Result<DecodedKey, String> {
    let (payload_b64, sig_b64) = body
        .split_once('.')
        .ok_or_else(|| "Key is malformed (missing signature)".to_string())?;

    let payload_bytes = B64
        .decode(payload_b64)
        .map_err(|_| "Key payload is not valid base64".to_string())?;
    let sig_bytes = B64
        .decode(sig_b64)
        .map_err(|_| "Key signature is not valid base64".to_string())?;

    if sig_bytes.len() != 64 {
        return Err("Key signature is the wrong length".to_string());
    }
    let mut sig_array = [0u8; 64];
    sig_array.copy_from_slice(&sig_bytes);
    let signature = Signature::from_bytes(&sig_array);

    verifying_key
        .verify(&payload_bytes, &signature)
        .map_err(|_| "Key signature did not verify (key was tampered with or is fake)".to_string())?;

    if payload_bytes.len() != PAYLOAD_V2_LEN {
        return Err(format!(
            "Key payload is the wrong length (expected {} bytes, got {})",
            PAYLOAD_V2_LEN,
            payload_bytes.len()
        ));
    }
    if payload_bytes[0] != PAYLOAD_V2_VERSION {
        return Err(format!(
            "Key uses an unsupported payload version (0x{:02x}). Please update Keyfire.",
            payload_bytes[0]
        ));
    }
    let tier = match payload_bytes[1] {
        PAYLOAD_V2_TIER_PRO => "pro".to_string(),
        other => return Err(format!("Key has an unknown tier (0x{:02x})", other)),
    };
    let exp_unix = u32::from_be_bytes([
        payload_bytes[2], payload_bytes[3], payload_bytes[4], payload_bytes[5],
    ]) as i64;
    let exp_dt = chrono::DateTime::from_timestamp(exp_unix, 0)
        .ok_or_else(|| "Key has an invalid expiry timestamp".to_string())?;
    let id_bytes = [payload_bytes[6], payload_bytes[7], payload_bytes[8], payload_bytes[9]];
    let id_hex = format!(
        "{:02x}{:02x}{:02x}{:02x}",
        id_bytes[0], id_bytes[1], id_bytes[2], id_bytes[3]
    );

    Ok(DecodedKey {
        email: None,
        exp: exp_dt.to_rfc3339(),
        tier,
        id: Some(id_hex),
    })
}

/// Decode + verify a legacy TRIGR-PRO. JSON-payload key. Kept forever so keys
/// already in the wild continue to work until they hit their exp timestamp.
fn verify_legacy_json(body: &str, verifying_key: &VerifyingKey) -> Result<DecodedKey, String> {
    let (payload_b64, sig_b64) = body
        .split_once('.')
        .ok_or_else(|| "Key is malformed (missing signature)".to_string())?;

    let payload_bytes = B64
        .decode(payload_b64)
        .map_err(|_| "Key payload is not valid base64".to_string())?;
    let sig_bytes = B64
        .decode(sig_b64)
        .map_err(|_| "Key signature is not valid base64".to_string())?;
    if sig_bytes.len() != 64 {
        return Err("Key signature is the wrong length".to_string());
    }
    let mut sig_array = [0u8; 64];
    sig_array.copy_from_slice(&sig_bytes);
    let signature = Signature::from_bytes(&sig_array);

    verifying_key
        .verify(&payload_bytes, &signature)
        .map_err(|_| "Key signature did not verify (key was tampered with or is fake)".to_string())?;

    let payload: LegacyPayload = serde_json::from_slice(&payload_bytes)
        .map_err(|e| format!("Key payload could not be parsed: {}", e))?;

    Ok(DecodedKey {
        email: Some(payload.email),
        exp: payload.exp,
        tier: payload.tier,
        id: payload.id,
    })
}

fn load_public_key() -> Result<VerifyingKey, String> {
    if PUBLIC_KEY_B64.starts_with("PLACEHOLDER") {
        return Err("public key not configured (placeholder build)".to_string());
    }
    let bytes = B64
        .decode(PUBLIC_KEY_B64)
        .map_err(|e| format!("base64 decode failed: {}", e))?;
    if bytes.len() != 32 {
        return Err(format!("expected 32 bytes, got {}", bytes.len()));
    }
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&bytes);
    VerifyingKey::from_bytes(&arr).map_err(|e| format!("VerifyingKey::from_bytes: {}", e))
}

// ── Helpers ─────────────────────────────────────────────────────────────────

fn compute_is_pro(state: &LicenceState) -> bool {
    // Real key path: signature verified, not expired, tier=pro.
    let key_pro = state.valid
        && state
            .expires_at
            .as_deref()
            .and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
            .map(|d| d.to_utc() > chrono::Utc::now())
            .unwrap_or(false)
        && state.tier.as_deref() == Some("pro");
    if key_pro {
        return true;
    }
    // Trial path: trial started locally and within the 14-day window.
    is_trial_active(state)
}

/// True while the 14-day trial is running. Does not require a key.
fn is_trial_active(state: &LicenceState) -> bool {
    if !state.trial_used {
        return false;
    }
    trial_days_remaining(state) > 0
}

/// Whole days remaining on the trial; 0 if not started or already expired.
fn trial_days_remaining(state: &LicenceState) -> i64 {
    let started = match state
        .trial_started_at
        .as_deref()
        .and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
    {
        Some(d) => d.to_utc(),
        None => return 0,
    };
    let ends = started + chrono::Duration::days(TRIAL_DURATION_DAYS);
    let now = chrono::Utc::now();
    if ends <= now {
        return 0;
    }
    let remaining = ends - now;
    // ceil() so "3 hours left" still reads as "1 day remaining" in UI
    (remaining.num_seconds() as f64 / 86_400.0).ceil() as i64
}

fn build_status(state: &LicenceState) -> LicenceStatus {
    let is_pro = compute_is_pro(state);
    let key_entered = state.key.as_ref().map(|k| !k.is_empty()).unwrap_or(false);
    let trial_active = is_trial_active(state);
    let trial_days = trial_days_remaining(state);

    // Key-derived status takes precedence over trial status when both exist —
    // the UI's headline state reflects the real licence, the trial fields
    // sit alongside for the trial-card display.
    let status = if !key_entered {
        if trial_active {
            "active".to_string() // Pro via trial
        } else if state.trial_used {
            "expired".to_string() // trial expired, no key
        } else {
            "no_key".to_string()
        }
    } else if !state.valid {
        "invalid".to_string()
    } else if is_pro {
        "active".to_string()
    } else {
        "expired".to_string()
    };

    LicenceStatus {
        is_pro,
        key_entered,
        status,
        product_name: if is_pro {
            "Keyfire Pro".to_string()
        } else {
            String::new()
        },
        expires_at: state.expires_at.clone(),
        email: state.email.clone(),
        key_id: state.key_id.clone(),
        trial_active,
        trial_days_remaining: trial_days,
        trial_used: state.trial_used,
        trial_offer_shown: state.trial_offer_shown,
    }
}

fn update_state(state: LicenceState) {
    let pro = compute_is_pro(&state);
    IS_PRO.store(pro, Ordering::SeqCst);

    if let Some(m) = LICENCE_STATE.get() {
        if let Ok(mut guard) = m.lock() {
            *guard = state.clone();
        }
    }
    save_to_local_settings(&state);
}

fn load_from_local_settings() -> LicenceState {
    let val = crate::config::load_local_settings_json();
    match val.get("licence") {
        Some(v) => serde_json::from_value::<LicenceState>(v.clone()).unwrap_or_else(|e| {
            warn!("[Keyfire] Failed to deserialize licence state: {}", e);
            LicenceState::default()
        }),
        None => LicenceState::default(),
    }
}

fn save_to_local_settings(state: &LicenceState) {
    let mut val = crate::config::load_local_settings_json();
    if let Some(obj) = val.as_object_mut() {
        match serde_json::to_value(state) {
            Ok(v) => {
                obj.insert("licence".to_string(), v);
            }
            Err(e) => {
                error!("[Keyfire] Failed to serialize licence state: {}", e);
                return;
            }
        }
    }
    crate::config::save_local_settings_json(&val);
}
