// Offline Ed25519 licence verification.
//
// Keys are signed strings of the form:
//   TRIGR-PRO-<base64url(payload_json)>-<base64url(signature)>
//
// The payload encodes { email, exp, tier, id }. The signature is verified
// against PUBLIC_KEY_B64 (which is the base64 of the 32-byte Ed25519 public
// key produced by `cargo run -- init` inside src-tauri/trigr-keygen).
// Verification is fully local — no network, no LemonSqueezy, no phone-home.

use log::{error, info, warn};
use serde::{Deserialize, Serialize};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, OnceLock};

use base64::engine::general_purpose::URL_SAFE_NO_PAD as B64;
use base64::Engine;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};

// ── Public key ──────────────────────────────────────────────────────────────
//
// Generated by `cargo run -- init` inside src-tauri/trigr-keygen.
// Matching private key is held offline by the founder; do not commit the private key.
const PUBLIC_KEY_B64: &str = "SSYMRvcbW18DXRMoBWt4hdI8rOWg0dXJnW1h92cpZ80";

// ── State ───────────────────────────────────────────────────────────────────

static IS_PRO: AtomicBool = AtomicBool::new(false);
static LICENCE_STATE: OnceLock<Mutex<LicenceState>> = OnceLock::new();

// ── Stored state ────────────────────────────────────────────────────────────

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct LicenceState {
    #[serde(default)]
    pub key: Option<String>,
    #[serde(default)]
    pub email: Option<String>,
    #[serde(default)]
    pub tier: Option<String>,
    #[serde(default)]
    pub expires_at: Option<String>,
    #[serde(default)]
    pub activated_at: Option<String>,
    #[serde(default)]
    pub valid: bool,
}

/// Returned to the frontend for UI display.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LicenceStatus {
    pub is_pro: bool,
    pub key_entered: bool,
    pub status: String, // "no_key" | "active" | "expired" | "invalid"
    pub product_name: String,
    pub expires_at: Option<String>,
    pub email: Option<String>,
}

#[derive(Deserialize)]
struct Payload {
    email: String,
    exp: String,
    tier: String,
    #[allow(dead_code)]
    id: Option<String>,
}

// ── Initialization ──────────────────────────────────────────────────────────

pub fn init() {
    let state = load_from_local_settings();
    let pro = compute_is_pro(&state);
    IS_PRO.store(pro, Ordering::SeqCst);
    let _ = LICENCE_STATE.set(Mutex::new(state));
    info!("[Trigr] Licence module initialized — is_pro: {}", pro);
}

pub fn is_pro() -> bool {
    IS_PRO.load(Ordering::SeqCst)
}

pub fn get_licence_status() -> LicenceStatus {
    let state = match LICENCE_STATE.get() {
        Some(m) => m.lock().unwrap_or_else(|e| e.into_inner()).clone(),
        None => LicenceState::default(),
    };
    build_status(&state)
}

// ── API ─────────────────────────────────────────────────────────────────────

/// Verify a pasted licence key, store it locally, and unlock Pro.
pub async fn activate_licence(key: String) -> Result<LicenceStatus, String> {
    let trimmed = key.trim().to_string();
    let payload = verify_key(&trimmed)?;

    // Reject expired keys before saving.
    let exp_dt = chrono::DateTime::parse_from_rfc3339(&payload.exp)
        .map_err(|_| "Key payload has an invalid expiry".to_string())?;
    if exp_dt.to_utc() < chrono::Utc::now() {
        return Err("This key has expired. Email admin@usetrigr.com for a new one.".to_string());
    }

    let state = LicenceState {
        key: Some(trimmed),
        email: Some(payload.email.clone()),
        tier: Some(payload.tier.clone()),
        expires_at: Some(payload.exp.clone()),
        activated_at: Some(chrono::Utc::now().to_rfc3339()),
        valid: true,
    };
    update_state(state.clone());
    info!(
        "[Trigr] Licence activated for {} (tier {}, expires {})",
        payload.email, payload.tier, payload.exp
    );
    Ok(build_status(&state))
}

/// Clear the saved licence and drop back to Free.
pub async fn deactivate_licence() -> Result<LicenceStatus, String> {
    let state = LicenceState::default();
    update_state(state.clone());
    info!("[Trigr] Licence deactivated");
    Ok(build_status(&state))
}

/// Re-verify the saved key (signature + expiry). No network — exists to
/// handle the case where the user has crossed the expiry date since they
/// last opened the app.
pub async fn check_and_revalidate() -> LicenceStatus {
    let state = match LICENCE_STATE.get() {
        Some(m) => m.lock().unwrap_or_else(|e| e.into_inner()).clone(),
        None => return build_status(&LicenceState::default()),
    };

    let key = match &state.key {
        Some(k) if !k.is_empty() => k.clone(),
        _ => return build_status(&state),
    };

    match verify_key(&key) {
        Ok(payload) => {
            let still_valid = chrono::DateTime::parse_from_rfc3339(&payload.exp)
                .map(|d| d.to_utc() > chrono::Utc::now())
                .unwrap_or(false);
            let new_state = LicenceState {
                key: Some(key),
                email: Some(payload.email),
                tier: Some(payload.tier),
                expires_at: Some(payload.exp),
                activated_at: state.activated_at,
                valid: still_valid,
            };
            update_state(new_state.clone());
            build_status(&new_state)
        }
        Err(e) => {
            warn!("[Trigr] Saved licence key failed re-verification: {}", e);
            let new_state = LicenceState {
                valid: false,
                ..state
            };
            update_state(new_state.clone());
            build_status(&new_state)
        }
    }
}

// ── Crypto + parsing ────────────────────────────────────────────────────────

fn verify_key(key: &str) -> Result<Payload, String> {
    // Key format: TRIGR-PRO.<base64url(payload)>.<base64url(signature)>
    // `.` is the separator — it is NOT in the base64url alphabet so it splits
    // cleanly even when payload/signature contain `-` or `_`.
    let body = key
        .strip_prefix("TRIGR-PRO.")
        .ok_or_else(|| "Not a Trigr licence key".to_string())?;
    let (payload_b64, sig_b64) = body
        .split_once('.')
        .ok_or_else(|| "Key is malformed (missing signature)".to_string())?;

    let payload_bytes = B64
        .decode(payload_b64)
        .map_err(|_| "Key payload is not valid base64".to_string())?;
    let sig_bytes = B64
        .decode(sig_b64)
        .map_err(|_| "Key signature is not valid base64".to_string())?;
    if sig_bytes.len() != 64 {
        return Err("Key signature is the wrong length".to_string());
    }
    let mut sig_array = [0u8; 64];
    sig_array.copy_from_slice(&sig_bytes);
    let signature = Signature::from_bytes(&sig_array);

    let verifying_key = load_public_key().map_err(|e| {
        format!(
            "This build of Trigr is missing its signing public key ({}). \
             Please reinstall the latest version.",
            e
        )
    })?;

    verifying_key
        .verify(&payload_bytes, &signature)
        .map_err(|_| "Key signature did not verify (key was tampered with or is fake)".to_string())?;

    serde_json::from_slice::<Payload>(&payload_bytes)
        .map_err(|e| format!("Key payload could not be parsed: {}", e))
}

fn load_public_key() -> Result<VerifyingKey, String> {
    if PUBLIC_KEY_B64.starts_with("PLACEHOLDER") {
        return Err("public key not configured (placeholder build)".to_string());
    }
    let bytes = B64
        .decode(PUBLIC_KEY_B64)
        .map_err(|e| format!("base64 decode failed: {}", e))?;
    if bytes.len() != 32 {
        return Err(format!("expected 32 bytes, got {}", bytes.len()));
    }
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&bytes);
    VerifyingKey::from_bytes(&arr).map_err(|e| format!("VerifyingKey::from_bytes: {}", e))
}

// ── Helpers ─────────────────────────────────────────────────────────────────

fn compute_is_pro(state: &LicenceState) -> bool {
    if !state.valid {
        return false;
    }
    let exp = match state.expires_at.as_deref() {
        Some(s) => s,
        None => return false,
    };
    let exp_dt = match chrono::DateTime::parse_from_rfc3339(exp) {
        Ok(d) => d.to_utc(),
        Err(_) => return false,
    };
    if exp_dt < chrono::Utc::now() {
        return false;
    }
    state.tier.as_deref() == Some("pro")
}

fn build_status(state: &LicenceState) -> LicenceStatus {
    let is_pro = compute_is_pro(state);
    let key_entered = state.key.as_ref().map(|k| !k.is_empty()).unwrap_or(false);

    let status = if !key_entered {
        "no_key".to_string()
    } else if !state.valid {
        "invalid".to_string()
    } else if is_pro {
        "active".to_string()
    } else {
        "expired".to_string()
    };

    LicenceStatus {
        is_pro,
        key_entered,
        status,
        product_name: if is_pro {
            "Trigr Pro".to_string()
        } else {
            String::new()
        },
        expires_at: state.expires_at.clone(),
        email: state.email.clone(),
    }
}

fn update_state(state: LicenceState) {
    let pro = compute_is_pro(&state);
    IS_PRO.store(pro, Ordering::SeqCst);

    if let Some(m) = LICENCE_STATE.get() {
        if let Ok(mut guard) = m.lock() {
            *guard = state.clone();
        }
    }
    save_to_local_settings(&state);
}

fn load_from_local_settings() -> LicenceState {
    let val = crate::config::load_local_settings_json();
    match val.get("licence") {
        Some(v) => serde_json::from_value::<LicenceState>(v.clone()).unwrap_or_else(|e| {
            warn!("[Trigr] Failed to deserialize licence state: {}", e);
            LicenceState::default()
        }),
        None => LicenceState::default(),
    }
}

fn save_to_local_settings(state: &LicenceState) {
    let mut val = crate::config::load_local_settings_json();
    if let Some(obj) = val.as_object_mut() {
        match serde_json::to_value(state) {
            Ok(v) => {
                obj.insert("licence".to_string(), v);
            }
            Err(e) => {
                error!("[Trigr] Failed to serialize licence state: {}", e);
                return;
            }
        }
    }
    crate::config::save_local_settings_json(&val);
}
